server:
  port: 8091

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

spring:
  application:
    name: message-service
          
eureka:
  client:
    instance:
      preferIpAddress: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
