server:
  port:8080

eureka:
  client:
    instance:
      preferIpAddress:true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

spring:
  application:
    name: gateway-service

zuul:
  sensitive-headers: Cookie,Set-Cookie
  ribbon:
    eager-load:
      enabled: true
  


management:
  endpoints:
    web:
      exposure:
        include: "*"